### PR TITLE
(fix) change to es6 syntax and upgrade tweenState

### PR DESCRIPTION
**Pull request by betiol**

### CODE REVIEW

**Comment by chagasaway** [comment]
Hey @betiol, I have just updated the code to use **Animated API** instead of **TimerMixin** and **TweenState** due to an issue report of memory leak.

In this **0.2.0** version I have updated as well the syntax to ES6, could you test this new 0.2.0 version and see if it's working as expected?

Thanks for the contribution!

**Comment by betiol** [comment]
I had problems today when updating the version of react native, I saw that we did at the same time haha. Ok I'll test the new version!

**Comment by betiol** [comment]
Great, is working perfectly, thank you. :+1:

**Comment by chagasaway** [comment]
Yes, when I started working on the issue report I saw that I will need to update to the ES6 syntax.

I will close this PR since the Animated API version is working.

Thanks for the PR, let me know if you found any other issues and be free to send another PR.

**Comment by betiol** [comment]
Ok, thx!

**Pull request closed without merging**
